apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id
  name: "test-username-pass"
  labels:
# so we know what type it is
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "A username and password credential from Kubernetes"
type: Opaque
stringData:
  username: myUsername
  password: 'Pa$$word'
