resources:
  - deployments.yaml
  - role-bindings.yaml
  - roles.yaml
  - service-accounts.yaml
  - services.yaml
configMapGenerator:
- name: jenkins-base-plugins
  files:
  - configuration/plugins.txt
- name: jenkins-base-customization
  files:
  - configuration/groovy/set-best-practice-settings.groovy
  - configuration/groovy/set-install-state.groovy
  - configuration/groovy/set-local-kubernetes-cloud.groovy
