apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-pods
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["create","delete","get","list","patch","update","watch"]
 - apiGroups: [""]
   resources: ["pods/exec"]
   verbs: ["create","delete","get","list","patch","update","watch"]
 - apiGroups: [""]
   resources: ["pods/log"]
   verbs: ["get","list","watch"]
 - apiGroups: [""]
   resources: ["events"]
   verbs: ["watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
rules:
 - apiGroups: [""]
   resources: ["secrets"]
   verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-config-maps
rules:
 - apiGroups: [""]
   resources: ["configmaps"]
   verbs: ["get","list","watch"]
