apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-master-manage-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-pods
subjects:
  - kind: ServiceAccount
    name: jenkins-master

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-master-read-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-secrets
subjects:
  - kind: ServiceAccount
    name: jenkins-master

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-master-read-config-maps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-config-maps
subjects:
  - kind: ServiceAccount
    name: jenkins-master
