apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  selector:
    app: jenkins
    role: master
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: jnlp
    port: 50000
    targetPort: 50000
    protocol: TCP